/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;

import static graph.Graph.graphBusinessTrip;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("B");
        graph.addVertex("C");

        graph.addEdges("A","B");
        graph.addEdges("B","C");
        graph.addEdges("A","C");

        System.out.println(graph.printGraph());

//        graph.removeVertex("B");
//        graph.removeEdge("A","B");



        Graph graph1 = new Graph();

        graph1.addVertex("Pandora" );
        graph1.addVertex("Arendelle");
        graph1.addVertex("Monstropolis");
        graph1.addVertex("Metroville");
        graph1.addVertex("Naboo");
        graph1.addVertex("Narnia");
        graph.addEdge("Pandora","Arendelle" , 150);
        graph.addEdge("Arendelle","Metroville" , 99);
        graph.addEdge("Monstropolis","Naboo" , 73);
        graph.addEdge("Arendelle","Monstropolis" , 42);
        graph.addEdge("Naboo","Narnia" , 37);

        ArrayList<String> arrayList = new ArrayList<>();

        arrayList.add("Arendelle");
        arrayList.add("Monstropolis");
        arrayList.add("Naboo");

        System.out.println(graphBusinessTrip(graph1,arrayList ));
    }
    }

