/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;

import static mergeSort.App.mergeSort;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testMergeSort() {
        int[] arr = new int[]{38, 27, 43, 3, 9, 82, 10};
        mergeSort(arr, 0, arr.length - 1);
        int[] expected= new int[]{3, 9, 10, 27, 38, 43, 82};
        assertArrayEquals(arr,expected);
    }
    @Test
    void secondTestMergeSort(){
        int[] arr = new int[]{6, 5, 12, 7, 10, 9, 1};
        mergeSort(arr, 0, arr.length - 1);
        int[] expected= new int[]{1,5,6,7,9,10,12};
        assertArrayEquals(arr,expected);
    }
}
