/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ArrayList<Integer>arrayList=new ArrayList<Integer>();
        arrayList.add(8);
        arrayList.add(4);
        arrayList.add(23);
        arrayList.add(42);
        arrayList.add(16);
        arrayList.add(15);
        QuickSort(arrayList,0, arrayList.size()-1);

        System.out.println(arrayList);
    }

    public static void QuickSort(ArrayList<Integer> arr, int left, int right) {
        if (left < right) {
            int position = Partition(arr, left, right);
            QuickSort(arr, left, position - 1);
            QuickSort(arr, position + 1, right);
        }
    }

    public static int Partition(ArrayList<Integer> arr, int left, int right) {
        int pivot = arr.get(right);
        int low = left - 1;
        for (int i = left; i < right; i++) {
            if (arr.get(i) <= pivot) {
                low++;
                Swap(arr, i, low);
            }

        }
        Swap(arr, right, low + 1);
        return low + 1;
    }
    public static void Swap(ArrayList<Integer>arr,int i, int low){
        int temp=arr.get(i);
        arr.set(i,arr.get(low));
        arr.set(low,temp);
    }

}

