/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import HashTable.Structure.HashMap;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        HashMap<String,String> countryCities=new HashMap<>();
        countryCities.set("Jordan","Amman");
        countryCities.set("United States","Washington D.C.");
        countryCities.set("United Kingdom","London");
        countryCities.set("Italy","Rome");
        countryCities.set("France","Paris");
        countryCities.set("Portugal","Lisbon");
        System.out.println(countryCities.keys());
        System.out.println(countryCities.Values());

    }




}
