/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static QuickSort.App.QuickSort;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test  public void QuickSortTest(){
        ArrayList<Integer> arrayList=new ArrayList<>();
        arrayList.add(8);
        arrayList.add(4);
        arrayList.add(23);
        arrayList.add(42);
        arrayList.add(16);
        arrayList.add(15);
        QuickSort(arrayList,0,arrayList.size()-1);
        ArrayList<Integer> arrayList2=new ArrayList<>();
        arrayList2.add(4);
        arrayList2.add(8);
        arrayList2.add(15);
        arrayList2.add(16);
        arrayList2.add(23);
        arrayList2.add(42);
        assertEquals(arrayList,arrayList2);


    }
    @Test  public void QuickSortTest2(){
        ArrayList<Integer> arrayList=new ArrayList<>();
        arrayList.add(8);
        arrayList.add(4);
        arrayList.add(13);
        arrayList.add(25);
        arrayList.add(7);
        arrayList.add(36);
        QuickSort(arrayList,0,arrayList.size()-1);
        ArrayList<Integer> arrayList2=new ArrayList<>();
        arrayList2.add(4);
        arrayList2.add(7);
        arrayList2.add(8);
        arrayList2.add(13);
        arrayList2.add(25);
        arrayList2.add(36);
        assertEquals(arrayList,arrayList2);


    }
}
