/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackAndQueue;

import StackAndQueue.stack.data.StackNode;
import StackAndQueue.stack.structure.Stack;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), ",");
    }




}
