/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blogChallenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testInsertSort(){
        int[] arr={4,23,42,8,16,15};
        int[] arrSorted=App.insertionSort(arr);
        int[] arrExpected={4,8,15,16,23,42};
        assertArrayEquals(arrExpected,arrSorted);

    }
}
